# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspaces\ws-aps\level2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_level_2(object):
    def setupUi(self, level_2):
        level_2.setObjectName("level_2")
        level_2.resize(531, 600)
        level_2.setStyleSheet("background-color: rgb(44, 128, 255);")
        self.centralwidget = QtWidgets.QWidget(level_2)
        self.centralwidget.setObjectName("centralwidget")
        self.intro_level2 = QtWidgets.QLabel(self.centralwidget)
        self.intro_level2.setGeometry(QtCore.QRect(80, 50, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.intro_level2.setFont(font)
        self.intro_level2.setObjectName("intro_level2")
        level_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(level_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        level_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(level_2)
        self.statusbar.setObjectName("statusbar")
        level_2.setStatusBar(self.statusbar)

        self.retranslateUi(level_2)
        QtCore.QMetaObject.connectSlotsByName(level_2)

    def retranslateUi(self, level_2):
        _translate = QtCore.QCoreApplication.translate
        level_2.setWindowTitle(_translate("level_2", "MainWindow"))
        self.intro_level2.setText(_translate("level_2", "nivel 2"))
