# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspaces\ws-aps\level.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_level_1(object):
    def setupUi(self, level_1):
        level_1.setObjectName("level_1")
        level_1.resize(515, 600)
        level_1.setStyleSheet("background-color: rgb(44, 128, 255);")
        self.centralwidget = QtWidgets.QWidget(level_1)
        self.centralwidget.setObjectName("centralwidget")
        self.intro_level1 = QtWidgets.QLabel(self.centralwidget)
        self.intro_level1.setGeometry(QtCore.QRect(80, 50, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.intro_level1.setFont(font)
        self.intro_level1.setObjectName("intro_level1")
        level_1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(level_1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        level_1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(level_1)
        self.statusbar.setObjectName("statusbar")
        level_1.setStatusBar(self.statusbar)

        self.retranslateUi(level_1)
        QtCore.QMetaObject.connectSlotsByName(level_1)

    def retranslateUi(self, level_1):
        _translate = QtCore.QCoreApplication.translate
        level_1.setWindowTitle(_translate("level_1", "MainWindow"))
        self.intro_level1.setText(_translate("level_1", "nivel 1"))
